### ISSUE TITLE
publish exe from github actions

### ISSUE THREAD

**Issue by timabell** [timabell/sln-items-sync#4]

**Comment by wgnf** [comment]
You could also publish it as a dotnet tool to nuget.org

I've done this a few times already, so I could probably help you out if you want

You can then do: `dotnet tool install -g <tool-name>`, to install it
and then run it using `<tool-name>`. You can find more info about that here: https://learn.microsoft.com/en-us/dotnet/core/tools/global-tools

**Comment by wgnf** [comment]
The holidays have been quite hectic, but I was finally able to take care of this issue here. Let me know what you think.

**Comment by timabell** [comment]
In and working, thanks for the contribution!
