### ISSUE TITLE
Interesting changes for SlnParser?

### ISSUE THREAD

**Issue by wgnf** [timabell/sln-items-sync#9]
Hey Tim,

its great to see something cool being built on top of something that I wrote a while ago :)
I just wanted to get in touch and ask if there are any changes that you made to `SlnParser` (now `SlnEditor`) that might be interesting for `SlnParser` itself?

**Comment by timabell** [comment]
The biggest change was to make all the immutable collections mutable, so you wouldn't necessarily want that in a pure reader.

SlnEditor can still be used as a parser/reader of course.

It's a bit too much of a hatchet job on the source to be turned into any useful contributions back upstream on this one I think, but of course its all unlicense so if you want to pick over the source and commit logs and pull anything or everything in then you are more than welcome to

**Comment by wgnf** [comment]
Okay thank you, maybe I'll have the chance to look at it during the christmas holidays
